"""Core graph and profile primitives for The Loom."""

from .graph_logic import BranchGraph, StoryNode
from .profile_engine import (
    MaturityOverride,
    ProfileRegistry,
    SceneLabelBenchmark,
    TextSceneCorrection,
    analyze_text_profile,
    analyze_visual_profile,
    build_maturity_profile,
    compute_tone_jitter_index,
    evaluate_scene_label_predictions,
)
from .profiles import ToneProfile
from .retrieval_engine import (
    ChunkMetadata,
    HierarchicalMemoryModel,
    NamespaceCompactionReport,
    NarrativeChunk,
    QueryBenchmark,
    RetrievalBudget,
    RetrievalHit,
    RetrievalIndex,
    RetrievalQualityMetrics,
    RetrievalQuery,
    RetrievalResponse,
    RetrievalRuntimeStats,
    UnresolvedThread,
    build_hierarchical_memory_model,
    evaluate_retrieval_quality,
    mean_reciprocal_rank,
    namespace_id,
    ndcg_at_k,
    precision_at_k,
)

__all__ = [
    "BranchGraph",
    "MaturityOverride",
    "ProfileRegistry",
    "SceneLabelBenchmark",
    "StoryNode",
    "TextSceneCorrection",
    "ToneProfile",
    "ChunkMetadata",
    "HierarchicalMemoryModel",
    "NarrativeChunk",
    "NamespaceCompactionReport",
    "QueryBenchmark",
    "RetrievalBudget",
    "RetrievalHit",
    "RetrievalIndex",
    "RetrievalQualityMetrics",
    "RetrievalQuery",
    "RetrievalResponse",
    "RetrievalRuntimeStats",
    "UnresolvedThread",
    "analyze_text_profile",
    "analyze_visual_profile",
    "build_hierarchical_memory_model",
    "build_maturity_profile",
    "compute_tone_jitter_index",
    "evaluate_retrieval_quality",
    "evaluate_scene_label_predictions",
    "mean_reciprocal_rank",
    "namespace_id",
    "ndcg_at_k",
    "precision_at_k",
]
